package com.communication.lib_core.tools

/**
 * Created by LG
 * on 2022/3/10  17:10
 * Description：
 */


const val EVENTBUS_TOKEN_SUCCESS = "EVENTBUS_TOKEN_SUCCESS"
const val EVENTBUS_LOGIN_SUCCESS = "EVENTBUS_LOGIN_SUCCESS"
const val EVENTBUS_LOGIN_FAIL = "EVENTBUS_LOGIN_FAIL"
const val EVENTBUS_LOGOUT_SUCCESS = "EVENTBUS_LOGOUT_SUCCESS"
const val EVENTBUS_TOAST_STRING = "EVENTBUS_TOAST_STRING"

const val EVENTBUS_HOME_APPS_SUCCESS = "EVENTBUS_HOME_APPS_SUCCESS"
const val EVENTBUS_APP_CLICK = "EVENTBUS_APP_CLICK"
const val EVENTBUS_MESSAGE_ITEM_CLICK = "EVENTBUS_MESSAGE_ITEM_CLICK"

const val EVENTBUS_CONTACT_CLICK = "EVENTBUS_CONTACT_CLICK"
const val EVENTBUS_CHANGE_PASSWORD_SUCCESS = "EVENTBUS_CHANGE_PASSWORD_SUCCESS"

const val EVENTBUS_TOKEN_INVALID = "EVENTBUS_TOKEN_INVALID"
const val EVENTBUS_CONTACT_USER_CLICK = "EVENTBUS_CONTACT_USER_CLICK"
const val EVENTBUS_CONTACT_ORG_CLICK = "EVENTBUS_CONTACT_ORG_CLICK"
const val EVENTBUS_CONTACT_SEARCH_USER_CLICK = "EVENTBUS_CONTACT_SEARCH_USER_CLICK"

const val EVENTBUS_CHECK_UPDATE_VERSION_BUTTON = "EVENTBUS_CHECK_UPDATE_VERSION_BUTTON"
const val EVENTBUS_CHECK_UPDATE_VERSION = "EVENTBUS_CHECK_UPDATE_VERSION"

const val EVENTBUS_UNREAD_MESSAGE = "EVENTBUS_UNREAD_MESSAGE"

const val EVENTBUS_USER_INFO = "EVENTBUS_USER_INFO"

const val EVENTBUS_MESSAGE_CLICK = "EVENTBUS_MESSAGE_CLICK"

const val EVENTBUS_GROUP_CLICK = "EVENTBUS_GROUP_CLICK"

const val EVENTBUS_ALARM_CLICK = "EVENTBUS_ALARM_CLICK"

const val EVENTBUS_ALARM_BADGE = "EVENTBUS_ALARM_BADGE"

const val EVENTBUS_EVENT_BADGE = "EVENTBUS_EVENT_BADGE"

const val EVENTBUS_MESSAGE_BADGE = "EVENTBUS_MESSAGE_BADGE"

const val EVENTBUS_EVENT_BACK = "EVENTBUS_EVENT_BACK"

const val EVENTBUS_EVENT_BOTTOM = "EVENTBUS_EVENT_BOTTOM"

const val EVENTBUS_GROUP_MEMBER = "EVENTBUS_GROUP_MEMBER"

const val EVENTBUS_GROUP_NAME = "EVENTBUS_GROUP_NAME"

const val EVENTBUS_CHATLOGIN = "EVENTBUS_CHATLOGIN"

const val EVENTBUS_CHATLISTUSER = "EVENTBUS_CHATLISTUSER"

const val EVENTBUS_GETMSGLIST = "EVENTBUS_GETMSGLIST"

const val EVENTBUS_MESSAGE_CONTENT = "EVENTBUS_MESSAGE_CONTENT"
const val EVENTBUS_VOICE_MESSAGE_CONTENT = "EVENTBUS_VOICE_MESSAGE_CONTENT"
const val EVENTBUS_SEND_MESSAGE = "EVENTBUS_SEND_MESSAGE"
const val EVENTBUS_VOICE_CLICK = "EVENTBUS_VOICE_CLICK"

const val EVENTBUS_CHAT_MESSAGE = "EVENTBUS_CHAT_MESSAGE"
const val EVENTBUS_CHAT_USER = "EVENTBUS_CHAT_USER"
const val EVENTBUS_CHAT_EVENT = "EVENTBUS_CHAT_EVENT"
const val EVENTBUS_CHAT_OUT_EVENT = "EVENTBUS_CHAT_OUT_EVENT"

const val EVENTBUS_CHAT_FINISH = "EVENTBUS_CHAT_FINISH"
const val EVENTBUS_CHAT_CONNECT = "EVENTBUS_CHAT_CONNECT"

const val EVENTBUS_CHAT_INCOME = "EVENTBUS_CHAT_INCOME"
const val EVENTBUS_CHAT_VOICE = "EVENTBUS_CHAT_VOICE"
const val EVENTBUS_CHAT_VIDEO = "EVENTBUS_CHAT_VIDEO"

const val EVENTBUS_CHAT_INCOMEEND = "EVENTBUS_CHAT_INCOMEEND"
